#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.3.9-jdk-8

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B package -Dmaven.test.skip=True  --file pom.xml
            - mv /opt/atlassian/pipelines/agent/build/target/drugref2.war /opt/atlassian/pipelines/agent/build/target/drugref2.$BITBUCKET_BUILD_NUMBER.war
            - curl -X POST "https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/opt/atlassian/pipelines/agent/build/target/drugref2.$BITBUCKET_BUILD_NUMBER.war"
            - COMMIT_MESSAGE=`git log --format=%B -n 1 $BITBUCKET_COMMIT`
            - echo "COMMIT_MESSAGE="\"$COMMIT_MESSAGE\" > /opt/atlassian/pipelines/agent/build/target/latestBuild
            - echo "BUILD_NUMBER="$BITBUCKET_BUILD_NUMBER >> /opt/atlassian/pipelines/agent/build/target/latestBuild
            - builddate=$(date +"%y.%m.%d-%H%M%S")
            - echo "BUILD_DATE="$builddate >> /opt/atlassian/pipelines/agent/build/target/latestBuild
            - echo "WAR_URL=https://bitbucket.org/oscaremr/drugref2/downloads/drugref2."$BITBUCKET_BUILD_NUMBER".war" >> /opt/atlassian/pipelines/agent/build/target/latestBuild
            - curl -X POST "https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/opt/atlassian/pipelines/agent/build/target/latestBuild"
                
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.2.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.4.3